### ISSUE TITLE
Documentation of MAPF algorithms used here

### ISSUE THREAD

**Issue by ljaniec** [open-rmf/mapf#6]
## Feature request

I would like to read more documentation about MAPF algorithms implemented/WIP/to-be-implemented in the Open-RMF.

### Description

At the moment I could not find any documentation besides the code in this repository. Will these be Rust-only implementations, or will it be possible to implement algorithms in C/C++/Python, for example?

**Comment by ros2torial** [comment]
Hi @mxgrey, 
Can you please provide flow diagram/architecture of this algorithm for understanding its core. It would be better if you can provide reference of related research paper.

**Comment by winstxnhdw** [comment]
Hi guys, I believe the implementation in this codebase is referenced from: https://arxiv.org/abs/1901.05506

**Comment by mxgrey** [comment]
A few points of clarification:
* This is a planning **framework** rather than an implementation of a single algorithm.
* There are several single-robot planning algorithms that are being provided, including A*, Dijkstra (forward and backward), and SIPP (Safe Interval Path Planning).
* The only multi-agent planning algorithm we have right now is Continuous-time Conflict Based Search, but we will add more over time.
* It is possible to write custom algorithms or custom domains _downstream_ (in your own projects/libraries) and use them with this framework, exactly the same as any algorithms that we provide out of the box from this repo.

> Will these be Rust-only implementations

I will be implementing all the algorithms in this repo using Rust. Since downstream projects can also implement algorithms for this framework, those projects are welcome to incorporate other languages into their algorithms using bindings if it suits them.

It's likely that I will create downstream packages to provide language bindings so that out-of-the-box planners that we implement with this library can be used in other languages, like C++ and Python.

**Comment by ljaniec** [comment]
@mxgrey Thank you for the clarification and your answers. I don't know Rust (yet?), but the C++/Python bindings will be helpful for sure in the future.
